- hosts: all
  vars:
    cjl_source_key: "./.ssh/id_cjl"
    cjl_dest_key: "{{ ansible_env.HOME }}/.ssh/id_cjl"
    bri_source_key: "./.ssh/id_bri"
    bri_dest_key: "{{ ansible_env.HOME }}/.ssh/id_bri"
    dotfile_branch: "master"
    enable_decryption: false
    ripgrep_version: 14.0.3
    fd_version: 8.7.1

  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      upgrade: yes
      force_apt_get: true
      update_cache: true
      cache_valid_time: 86400 #One day
      state: present
    tags:
      - setup

  tasks:
    - include: tasks/core.yml
    - include: tasks/ssh.yml
    - include: tasks/base16.yml
    - include: tasks/nvim.yml
    - include: tasks/tmux.yml
    - include: tasks/zsh.yml
    - include: tasks/dotfiles.yml
    - include: tasks/p-aliases.yml
