- hosts: localhost
  vars:
    cjl_source_key: "./.ssh/id_cjl"
    cjl_dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_cjl"
    bri_source_key: "./.ssh/id_bri"
    bri_dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_bri"
    enable_decryption: false

  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
    tags:
      - setup

  tasks:
    - include: tasks/ssh.yml
    - include: tasks/base16.yml
    - include: tasks/dotfiles.yml
