- hosts: all
  vars:
    cjl_source_key: "./.ssh/id_cjl"
    cjl_dest_key: "{{ ansible_env.HOME }}/.ssh/id_cjl"
    bri_source_key: "./.ssh/id_bri"
    bri_dest_key: "{{ ansible_env.HOME }}/.ssh/id_bri"
    dotfile_branch: "master"
    enable_decryption: false
    ripgrep_version: 15.1.0
    fd_version: 10.3.0
    linux_distro: "{{ ansible_family_os }}"
    use_zsh: true

  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      upgrade: no
      force_apt_get: true
      update_cache: true
      cache_valid_time: 86400 #One day
      state: present
    when: ansible_os_family == "Debian"

  - name: Update Package Manager
    become: true
    pacman:
      update_cache: true
      state: present
    when: ansible_os_family == "Archlinux"

  tasks:
    - include_tasks: setup-Debian.yml
      when: ansible_os_family == 'Debian'
      tags: [setup, core, ssh, base16, nvim, tmux, zsh, dotfiles, private_aliases]

    - include_tasks: setup-additional-Debian.yml
      when: ansible_os_family == 'Debian' and ansible_architecture == "x86_64"
      tags: [brave, nix, ghostty, additional]

    - include_tasks: setup-Archlinux.yml
      when: ansible_os_family == "Archlinux"
      tags: [setup, core, ssh, base16, nvim, tmux, zsh, dotfiles, hyprland, private_aliases]

    - include_tasks: setup-additional-Archlinux.yml
      when: ansible_os_family == "Archlinux"
      tags: [brave, nix, ghostty, spotify, additional, yay]
