- name: Cloning base16
  ansible.builtin.git:
    repo: 'https://github.com/chriskempson/base16-shell.git'
    dest: "{{ lookup('env', 'HOME') }}/.config/base16-shell"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: master
  tags:
    - setup
    - base16
