# Core packages
- name: Install developer packages
  become: yes
  apt:
    name:
      - build-essential
      - cmake
      - cppcheck
      - gdb
      - git
      - ssh
      - libwrap0
      - ncurses-term 
      - openssh-server
      - openssh-sftp-server
      - ssh-import-id
      - libgoogle-glog-dev
      - libspnav-dev
      - libusb-dev
      - lsb-release
      - software-properties-common
      - wget
      - net-tools
      - curl
      - bc
      - ansible
      - wl-clipboard
  tags:
    - setup
    - core
