- name: Cloning dotfiles
  ansible.builtin.git:
    repo: 'git@github.com:brucechanjianle/dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: master
  tags:
    - setup
    - dotfiles

- name: Setup dotfiles
  shell: cd $HOME/.dotfiles && ./ubuntu
  tags:
    - setup
    - dotfiles

