- name: Cloning dotfiles
  ansible.builtin.git:
    repo: 'https://github.com/BruceChanJianLe/dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: master
    bare: true
  tags:
    - setup
    - dotfiles

- name: Setup dotfiles
  shell: /usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME checkout master -f && source $HOME/.bashrc && config config --local status.showUntrackedFiles no
  tags:
    - setup
    - dotfiles

