- name: Cloning dotfiles
  ansible.builtin.git:
    repo: 'https://github.com/BruceChanJianLe/dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: master
    bare: true
  tags:
    - setup
    - dotfiles

- name: Checkout to master branch
  shell: /usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME checkout "{{ dotfile_branch }}" -f
  tags:
    - setup
    - dotfiles

- name: Stop showing untrack files
  shell: /usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME config --local status.showUntrackedFiles no
  tags:
    - setup
    - dotfiles

