- name: Make backup .bashrc
  ansible.builtin.copy:
    src: "{{ ansible_env.HOME }}/.bashrc"
    dest: "{{ ansible_env.HOME }}/.bashrc.ori"
    mode: 0664
    decrypt: false
  tags:
  - setup
  - dotfiles

- name: Check .bash_aliases exist
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.bash_aliases"
  register: bal
  tags:
  - setup
  - dotfiles

- name: Make backup .bash_aliases
  ansible.builtin.copy:
    src: "{{ ansible_env.HOME }}/.bash_aliases"
    dest: "{{ ansible_env.HOME }}/.bash_aliases.ori"
    mode: 0664
    decrypt: false
  when: bal.stat.exists
  tags:
  - setup
  - dotfiles

- name: Cloning dotfiles
  ansible.builtin.git:
    repo: 'https://github.com/BruceChanJianLe/dotfiles.git'
    dest: "{{ ansible_env.HOME }}/.dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: master
    bare: true
  tags:
    - setup
    - dotfiles

- name: Checkout to your branch
  shell: /usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME checkout "{{ dotfile_branch }}" -f
  tags:
    - setup
    - dotfiles

- name: Stop showing untrack files
  shell: /usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME config --local status.showUntrackedFiles no
  tags:
    - setup
    - dotfiles

- name: Restore original .bashrc
  ansible.builtin.copy:
    src: "{{ ansible_env.HOME }}/.bashrc.ori"
    dest: "{{ ansible_env.HOME }}/.bashrc"
    mode: 0664
    decrypt: false
  when: "{{ use_zsh }}"
  tags:
  - setup
  - dotfiles

- name: Restore original .bash_aliases
  ansible.builtin.copy:
    src: "{{ ansible_env.HOME }}/.bash_aliases.ori"
    dest: "{{ ansible_env.HOME }}/.bash_aliases"
    mode: 0664
    decrypt: false
  when: "{{ use_zsh }}"
  tags:
  - setup
  - dotfiles
