- name: Install required packages
  ansible.builtin.apt:
    name:
      - libgtk-4-dev
      - libadwaita-1-dev
    state: present
    update_cache: yes
  become: yes

- name: Cloning ghostty
  ansible.builtin.git:
    repo: 'https://github.com/ghostty-org/ghostty.git'
    dest: "{{ ansible_env.HOME }}/reference/ghostty.git"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: master
    bare: true
  tags:
    - setup
    - ghostty

- name: Configure remote for correct fetch behavior
  ansible.builtin.shell: |
    git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
  args:
    chdir: "{{ ansible_env.HOME }}/reference/ghostty.git"
  become: no
  tags:
    - setup
    - ghostty

- name: Perform a git fetch
  ansible.builtin.shell: |
    git fetch
  args:
    chdir: "{{ ansible_env.HOME }}/reference/ghostty.git"
  become: no
  tags:
    - setup
    - ghostty

- name: Create v1.0.0 Git worktree
  ansible.builtin.shell: |
    git worktree add v1.0.0 v1.0.0
  args:
    chdir: "{{ ansible_env.HOME }}/reference/ghostty.git"
  become: no
  tags:
    - setup
    - ghostty

- name: Build Ghostty with Nix
  ansible.builtin.shell: |
    . /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
    nix develop --accept-flake-config --command $(which zsh) -c "which zig | xargs -I {} sudo {} build -p /usr/local -Doptimize=ReleaseFast"
  args:
    chdir: "{{ ansible_env.HOME }}/reference/ghostty.git/v1.0.0"
  become: no
  tags:
    - setup
    - ghostty
