- name: Install ghostty
  become: yes
  ansible.builtin.pacman:
    name: ghostty
  tags:
    - setup
    - ghostty
    - additional

# Clone ghostty config
- name: Check if ghostty directory is empty
  find:
    paths: "{{ ansible_env.HOME }}/.config/ghostty"
    file_type: any
  register: ghostty_contents
  tags:
    - setup
    - ghostty
    - additional

- name: Clone ghotty config repo if dir is empty
  git:
    repo: 'https://github.com/brucechanjianle/ghostty.git'
    dest: "{{ ansible_env.HOME }}/.config/ghostty"
    force: yes
  when: ghostty_contents.matched == 0
  tags:
    - setup
    - ghostty
    - additional
