- name: Check if Nix is installed
  command: which nix
  register: nix_installed
  changed_when: false
  ignore_errors: true
  tags:
    - setup
    - nix
    - additional

- name: Download Nix installer
  ansible.builtin.get_url:
    url: https://nixos.org/nix/install
    dest: /tmp/nix-install.sh
    mode: '0755'
  when: nix_installed.rc != 0
  tags:
    - setup
    - nix
    - additional

- name: Run Nix installer interactively
  ansible.builtin.expect:
    command: "bash /tmp/nix-install.sh --daemon"
    responses:
      "\\[y/n\\]": "y"
      "Nix won't work in active shell sessions until you restart them.": ""
      "I don't support your init system yet; you may want to add nix-daemon manually.": ""
    timeout: 600
  become: yes
  when: nix_installed.rc != 0
  tags:
    - setup
    - nix
    - additional

- name: Remove Nix installer script
  ansible.builtin.file:
    path: /tmp/nix-install.sh
    state: absent
  when: nix_installed.rc != 0
  tags:
    - setup
    - nix
    - additional
