- name: Install neovim and dependencies
  become: yes
  ansible.builtin.pacman:
    name:
      - neovim
      - ripgrep
      - fd
      - luarocks
      - imagemagick
      - python-virtualenv
  tags:
    - setup
    - nvim

- name: Clone nvim
  ansible.builtin.git:
    repo: 'https://github.com/brucechanjianle/nvim.git'
    dest: "{{ ansible_facts['env']['HOME'] }}/.config/nvim"
  tags:
    - setup
    - nvim

- name: Install nvim plugins
  become: no
  shell: 'nvim --headless "+Lazy! sync" +qa > /dev/null 2>&1'
  ignore_errors: true
  tags:
    - setup
    - nvim
