- name: Clone zsh
  ansible.builtin.git:
    repo: 'https://github.com/brucechanjianle/zsh.git'
    dest: "{{ ansible_env.HOME }}/.config/zsh"
    version: "{{ dotfile_branch }}"
  tags:
    - setup
    - zsh

- name: Install zsh
  shell: "{{ ansible_env.HOME }}/.config/zsh/install_zsh.bash -a true"
  tags:
    - setup
    - zsh

- name: Change shell to zsh
  become: yes
  shell: sudo chsh -s $(which zsh)
  tags:
    - setup
    - zsh

- name: Install fzf
  become: yes
  apt:
    name:
      - fzf
  tags:
    - setup
    - zsh
